unless defined?(CONSTANTS_LOADED)
  DATABASE_URL = ENV["DATABASE_URL"]

  TOKEN = ENV["TOKEN"]
  CLIENT_ID = ENV["CLIENT_ID"]

  COMMAND_CHANNEL_ID = ENV["TIMER_COMMAND_CHANNEL_ID"].to_i
  TIMER_CHANNEL_ID = ENV["TIMER_CHANNEL_ID"].to_i
  TIMER_ALERT_CHANNEL_ID = ENV["TIMER_ALERT_CHANNEL_ID"].to_i
  EARTHQUAKE_ALERT_CHANNEL_ID = ENV["EARTHQUAKE_ALERT_CHANNEL_ID"]
  EARTHQUAKE_ALERT_MESSAGE = ENV["EARTHQUAKE_ALERT_MESSAGE"]
  TIMER_CHANNEL_REFRESH_RATE = (ENV["TIMER_CHANNEL_REFRESH_RATE"] || 10).to_i
  TIMER_ALERT_CHANNEL_REFRESH_RATE = (ENV["TIMER_ALERT_CHANNEL_REFRESH_RATE"] || 1).to_i
  UPDATE_TIMERS_CHANNEL = true
  UPDATE_TIMERS_ALERT_CHANNEL = true

  CONSTANTS_LOADED = true
end
