unless defined?(CONSTANTS_LOADED)
  DATABASE_URL = ENV["DATABASE_URL"]

  TOKEN = ENV["TOKEN"]
  CLIENT_ID = ENV["CLIENT_ID"]

  USE_EVERYONE_ALERT = ENV["USE_EVERYONE_ALERT"].to_s == "true"
  USE_MESSAGE_THREE = ENV["USE_MESSAGE_THREE"].to_s == "true"
  USE_DISCORD_TIMESTAMPS = ENV["USE_DISCORD_TIMESTAMPS"].to_s == "true"
  SHOW_FUTURE_WINDOW = ENV["SHOW_FUTURE_WINDOW"].to_s == "true"
  CONDENSE_FUTURE_WINDOW = ENV["CONDENSE_FUTURE_WINDOW"].to_s == "true"

  COMMAND_CHANNEL_ID = ENV["TIMER_COMMAND_CHANNEL_ID"].to_i
  TIMER_CHANNEL_ID = ENV["TIMER_CHANNEL_ID"].to_i
  TIMER_ALERT_CHANNEL_ID = ENV["TIMER_ALERT_CHANNEL_ID"].to_i
  EARTHQUAKE_ALERT_CHANNEL_ID = ENV["EARTHQUAKE_ALERT_CHANNEL_ID"]
  EARTHQUAKE_ALERT_MESSAGE = ENV["EARTHQUAKE_ALERT_MESSAGE"]
  TIMER_CHANNEL_REFRESH_RATE = (ENV["TIMER_CHANNEL_REFRESH_RATE"] || 10).to_i
  TIMER_ALERT_CHANNEL_REFRESH_RATE = (ENV["TIMER_ALERT_CHANNEL_REFRESH_RATE"] || 1).to_i
  TIMER_MESSAGE_THREE_ORDER = ENV["TIMER_MESSAGE_THREE_ORDER"] || ""
  UPDATE_TIMERS_CHANNEL = true
  UPDATE_TIMERS_ALERT_CHANNEL = true

  TIMER_CHANNEL_WEBHOOK_URL = ENV["TIMER_CHANNEL_WEBHOOK_URL"]

  COLUMN_1 = 30
  COLUMN_2 = 20
  COLUMN_3 = 15
  COLUMN_4 = 22

  CONSTANTS_LOADED = true
end
